
import { useRef } from "react";
import QRCode from 'react-qr-code'; // Import react-qr-code

export default function QrCode({ passengerInfo, data, onBack, onFinish }) {
  const qrPrintRef = useRef(null);
  const printQR = () => window.print();

  if (!passengerInfo) {
    return <div>Loading...</div>;  // Show a loading state if passengerInfo is not yet available
  }

  return (
    <div className="boarding-manual-section">
      <h4 className="boarding-manual-subtitle">QR Code</h4>
      <p className="boarding-manual-desc">A ticket QR has been generated by the system for this booking.</p>

      <div id="qr-print" ref={qrPrintRef} className="qr-ticket">
        <div className="qr-ticket__header">
          <div className="qr-ticket__title">Boarding Pass</div>
          <div className="qr-ticket__meta">
            <span>Date: {data.departureDate || "—"}</span>
            <span>Time: {data.departureTime || "—"}</span>
          </div>
        </div>

        <div className="qr-ticket__body">
          <div className="qr-faux">
            {/* Generate the QR code with react-qr-code */}
            <QRCode value={data.qrCodeID} size={256} />
          </div>
          <div className="qr-lines qr-lines--lg">
            <div>Passenger: <strong>{passengerInfo.firstName} {passengerInfo.lastName}</strong></div>
            <div>Ticket Code: <strong>{data.qrCodeID}</strong></div>
            <div>From: <strong>{data.origin || "—"}</strong></div>
            <div>Destination: <strong>{data.destination || "—"}</strong></div>
            <div>Paid Amount: <strong>₱ {data.paidAmount || "0.00"}</strong></div>
            <div>Payment Status: <strong>{data.paymentStatus || "—"}</strong></div>
            <div>Source: <strong>{passengerInfo.platformSource || "—"}</strong></div>
          </div>
        </div>

        <div className="qr-ticket__footer">
          <div className="qr-ticket__note">Please present this ticket upon boarding.</div>
        </div>
      </div>

      <div className="wizard-actions-split">
        <button className="boarding-modal-btn boarding-modal-cancel" onClick={onBack}>Back</button>
        <div style={{ display: "flex", gap: 8 }}>
          <button className="boarding-modal-btn" onClick={printQR} title="Print or save as PDF">Print Ticket (PDF)</button>
          <button className="boarding-manual-next" onClick={onFinish} title="Finish">Finish</button>
        </div>
      </div>
    </div>
  );
}
